name: QuoVadis
favicon: null
layout_spectrum: 0.25965
typography_spectrum: 0.48092
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000106'
    - '#bda8fb'
    - '#1995fa'
    - '#fb5c6b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
