name: QuoVadis
favicon: null
layout_spectrum: 0.9695163348224014
typography_spectrum: 0.06510266405530274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7328887654002756
  lightness: 0.9277887204661965
  saturation: 0.5310448268428445
  rhythmicContrast: 0.8864091925788671
purpose: []
